[config]
schemaVersion = "1.0.0"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "LopyMine"
name = "PatPat"
description = "Allows you to PAT your friends in Peak! Also changes the gameplay a little, not just visual!"
websiteUrl = ""
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/PatPat/release/net.lopymine.patpat.PatPat.dll"
target = "plugins/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[[build.copy]]
source = "../../data"
target = "plugins/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak" ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods" ]
